CREATE DATABASE ag_amorosovyt;
use ag_amorosovyt;

-- CREACION DE TABLAS

CREATE TABLE CLIENTE(
EMAIL VARCHAR (60),
ID VARCHAR(15) PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
TELEFONO INT(30) NOT NULL
);

CREATE TABLE TARJETA(
NOMBRE VARCHAR(15),
FOREIGN KEY (NOMBRE) REFERENCES CLIENTE (ID)	
NUMERO_TARJ INT(25) PRIMAR KEY,
ENTIDAD_FINANCIERA VARHCAR(15) NOT NULL,
CS INT(4) NOT NULL
);

CREATE TABLE CONSULTA(
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR (30) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,	
ID INT(5) AUTO_INCREMENT PRIMARY KEY,
TEXTO TEXT(10000) NOT NULL,
TIPO_VIAJE VARCHAR(5),
ORIGEN VARCHAR(35),
DESTINO VARCHAR(35),
FECHA_SALIDA DATE,
FECHA_LLEGADA DATE,
TRASLADO CHAR(3),
ALOJAMIENTO CHAR(3),
SEGURO_MEDICO CHAR(3)
);

CREATE TABLE PROMOS(
ID VARCHAR(15) PRIMARY KEY,
URL_IMAGEN VARCHAR(1000) NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
PAIS VARCHAR(50) NOT NULL,
INCLUYE VARCHAR(120) NOT NULL,
PRECIO INT(8)NOT NULL
);

CREATE TABLE USUARIO(
NOMBRE VARCHAR(35) NOT NULL,
CI INT(9) PRIMARY KEY,
CONTRA VARCHAR(50) NOT NULL
);